---
title: "word_cloud"
author: "Emilio M. Bruna"
date: "8/25/2021"
output: html_document
---

For more info on word-clouds see [this tutorial](https://www.geeksforgeeks.org/generating-word-cloud-in-r-programming/)


```{r setup, include = FALSE}


# install the required packages
# install.packages("tm")		 # for text mining
# install.packages("SnowballC") # for text stemming
# install.packages("wordcloud") # word-cloud generator
# install.packages("RColorBrewer") # color palettes

# load the packages
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("tidyverse")

text = readLines(file.choose())

text<-tolower(text)
docs = Corpus(VectorSource(text))   

# Convert the text to lower case
docs = tm_map(docs, 
        content_transformer(tolower))


# Remove numbers
docs = tm_map(docs, removeNumbers)
  
# Remove white spaces
docs = tm_map(docs, stripWhitespace)


dtm = TermDocumentMatrix(docs)

m = as.matrix(dtm)
v = sort(rowSums(m), decreasing = TRUE)
d = data.frame(word = names(v), freq = v)
head(d, 10)


document_tm_clean <- removeSparseTerms(dtm, 0.8)
document_tm_clean_mat <- as.matrix(document_tm_clean)

 
# Graph 3: commonality word cloud : first top 2000 common words across classes
png("#103_commonality_wordcloud.png", width = 480, height = 480)
commonality.cloud(document_tm_clean_mat, max.words=2000, random.order=FALSE)
dev.off()


wordcloud(words = d$word,
		freq = d$freq,
		min.freq = 1,
		max.words = 200,
		random.order = FALSE,
		random.color=TRUE,
		rot.per = 0.35,
		colors = brewer.pal(8, "Dark2"))

# # Graph 3: commonality word cloud : first top 2000 common words across classes
# png("#103_commonality_wordcloud.png", width = 480, height = 480)
# commonality.cloud(d, max.words=2000, random.order=FALSE)
# dev.off()

```





```{r setup, include = FALSE}

library("RColorBrewer")
library("tidyverse")

text = readLines(file.choose())

text<-tolower(text)

docs = Corpus(VectorSource(text))   

# Convert the text to lower case
docs = tm_map(docs, 
        content_transformer(tolower))

# Remove numbers
docs = tm_map(docs, removeNumbers)
  
# Remove white spaces
docs = tm_map(docs, stripWhitespace)


dtm = TermDocumentMatrix(docs)

m = as.matrix(dtm)
v = sort(rowSums(m), decreasing = TRUE)
d = data.frame(word = names(v), freq = v)
head(d, 10)


plot<-d %>%
  arrange(freq) %>%    # First sort by val. This sort the dataframe but NOT the factor levels
  mutate(word=factor(word, levels=word)) %>%   # This trick update the factor levels
  ggplot( aes(x=word, y=freq)) +
    geom_segment(aes(xend=word, yend=0)) +
    geom_point( size=1, color="orange") +
    # scale_x_discrete(guide = guide_axis(n.dodge=2))+  
    coord_flip() +
    theme_bw() +
    # theme(axis.text.y =element_text(size=2))+
    xlab("")
 
plot



```
