---
title: "Student Learning Objectives: International"
author: "Emilio M. Bruna"
date: "7/14/2021"
output: html_document
weight: 8
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# library(gridExtra)
library(kableExtra)
# library(egg)
# library(magick)
# library(citr)
```

```{r slo1, echo=FALSE,message = FALSE,warning=FALSE}
sl_objectives_2 <- read_csv("secondary_objectives.csv") %>% 
  replace_na(list('Biological Sciences Objectives'="", 'This course’s Objectives (This course will…)'=""))

kable(sl_objectives_2,
      # digits = 2,
      align="l",
      format="html",
      row.names = FALSE,
      escape= TRUE,
      booktabs=T,
      linesep = "",
      ) %>% 
  kable_paper(full_width = F) %>%
  row_spec(0, bold = T, italic = F, color="darkgreen") %>% 
  # row_spec(1, bold = F, italic = T, color="darkgreen") %>% 
  # column_spec(1, bold = F, border_right = T) %>%
  # column_spec(2, width = "5em", background = "white",border_right = T) %>% 
  #   pack_rows("WHY ARE WE FASCINATED BY TROPICAL RAIN FORESTS?", 1, 4) %>%
  # pack_rows("THE ORIGINS AND MAINTENANCE OF TROPICAL BIODIVERSITY", 5, 14) %>%
  # pack_rows("HUMANS & RAIN FORESTS", 15, 22) %>%
  # pack_rows("THE FUTURE OF TROPICAL RAIN FORESTS", 23, 30) %>%
  # pack_rows("Finals Week", 31, 31) %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = T,
                latex_options="scale_down",
                font_size = 14,
                position = "left")

```