---
title: "Reading"
author: "Emilio M. Bruna"
date: "8/20/2021"
output: html_document
---
  * Staver *et. al.* 2011. The global extent and determinants of savanna and forest as alternative states. *Science* 334: 230-232.
  * zu Ermgassen *et. al.* 2020. The origin, supply chain, and deforestation risk of Brazil’s beef exports. *Proceedings of the National Academy of Sciences*. 117(50):31770-31779
  * Raby, Megan. 2017. The Colonial Origins of Tropical Field Stations. American Scientist 105(4): 216-223. 
  * Lawal, Shola. 2020. Our Endless Appetite For Chocolate Has Bitter Environmental Consequences. Huffington Post. [link](https://tinyurl.com/y6curgmn)
  * Priscilla Jolly. 2021. ‘Godzilla vs. Kong’: Monster movies evoke adventure but also ‘dangers’ of tropics. *The Conversation*. [link](https://theconversation.com/godzilla-vs-kong-monster-movies-evoke-adventure-but-also-dangers-of-tropics-158105)
  * Joseph McQuade. 2019. Colonialism’s role in the overexploitation of natural resources. *The Conversation*. [link](https://theconversation.com/earth-day-colonialisms-role-in-the-overexploitation-of-natural-resources-113995)
* Wulf D. Hund & Charles W Mills. 2016. Comparing black people to monkeys has a long, dark simian history. *The Conversation*. [link](https://theconversation.com/comparing-black-people-to-monkeys-has-a-long-dark-simian-history-55102)

https://time.com/6086973/jungle-cruise-disney-theme-park-ride/ 
ndigenous
https://theconversation.com/why-amazonian-forest-peoples-are-counter-mapping-their-ancestral-lands-84474

Tropical cities; https://theconversation.com/healthy-happy-and-tropical-worlds-fastest-growing-cities-demand-our-attention-112069

palm oil: 
https://theconversation.com/how-palm-oil-became-the-worlds-most-hated-most-used-fat-source-161165

https://www.nytimes.com/2020/04/09/climate/animals-humans-virus-covid.html

https://www.nytimes.com/2019/08/27/world/africa/congo-angola-rainforest-fires.html

https://www.nytimes.com/2018/12/10/world/americas/amazon-illegal-mining.html

https://www.nytimes.com/2018/10/09/science/fruit-color-evolution.html

https://www.nytimes.com/2018/02/14/science/peru-yaguas-national-park.html

https://www.nytimes.com/2021/04/02/opinion/international-world/juma-people-brazil-amazon.html?searchResultPosition=10

https://www.nytimes.com/2006/05/21/travel/tmagazine/21T-JUNGLE.html?searchResultPosition=18

https://www.nytimes.com/2021/03/11/climate/nature-conservation-30-percent.html?searchResultPosition=14