---
title: "Complete Syllabus"
author: "Emilio M. Bruna"
date: "7/12/2021"
output: html_document
weight: 5
---
## IDS 2935 The Future of Tropical Rain Forests (Quest 2)
## Fall 2021

### I. Course Information

  * **Meeting Day, Time,& Location:**  
      Tuesday Period 4 (10:40 AM - 11:30 AM) in AND101 *AND*  
      Thursday Period 4-5 (10:40 AM - 12:35 PM) in WM 0202

  * **Instructor:**  
      Prof. Emilio M. Bruna  
      Office location: 380 Grinter Hall  
      Office hours: Location and Time TBA (and by appointment)  
      Phone: (352) 846-0634
      email: embruna@ufl.edu

  * **GenEd Designations**  
  
    * **Primary GenEd Designation**: Biological Sciences  
    * **Secondary GenEd Designation (if seeking)**: International (N)  
    
      _A minimum grade of C is required for general education_  
    * **Writing designation**: No writing designation

* **Course Description**
    
    Tropical Rain Forests cover approximately 15% of the Earth’s land surface but contain over 50% of the world’s biodiversity. They are also the home to millions of people, the source of products central to our lives, shape global climate, and are being cleared at unprecedented rates. Students in this class will investigate the same fundamental questions asked by scientists that study rain forests: Why are we fascinated by rain forests? How have stereotypes about them permeated everything from pop culture to international relations? What gave rise to their remarkable biodiversity? What are the drivers and consequences of deforestation? Is rain forest conservation compatible with socioeconomic development? 
    
    Students will explore these questions by reading and discussing a research studies, gathering and analyzing multidisciplinary data, interviewing people engaged in forest-related activities, and by reflecting on the consequences for rain forests of our choices as consumers, scholars, and community members. The course is taught in a non-traditional format: in-class sessions will be devoted to activities ranging from conversations with journalists, scientists, and conservation practitioners based in tropical countries to gathering and analyzing data on deforestation to reading and discussing scientific studies. There might be a field trip to a museum or supermarket. There might even be an occasional lecture. Instead of readings from a textbook, most weeks we will read a scientific study or some texts intended for a general audience (e.g., newspaper articles, chapters from memoir). The assignments are designed to maximize personal reflection and creativity…and yes, you can actually get credit for watching movies such as Predator, Rio, and Apocalypse Now. Welcome to the Jungle!

* **Required & Recommended Course Materials**

    **Required (purchase/rent):** Juniper, T. (2019). Rainforest: Dispatches from Earth's Most Vital Frontlines. Island Press. (456 pp). ISBN-13: 9781642830736 [approx. $8 (used), $14-18 (new), $20 (electronic)].

    *Additional required readings will be made available on course Canvas site* 

    **Recommended:** None

### II. Coursework & Schedule

1. **List of Graded Work**

2. **Weekly Course Schedule** 

### III. Grading

**3. Statement on Attendance and Participation **

  Requirements for class attendance and make-up exams, assignments, and other work in this course are consistent with university policies that can be found at: https://catalog.ufl.edu/UGRD/academic-regulations/attendance-policies/
  
  * **Attendance:** Though attendance is not required, most of the required assignments are completed in class. They are designed so that one could complete them independently, but by doing them in class you will benefit from working collaboratively with the other students. 
  * **Participation:** Consistent informed, thoughtful, and considerate class participation is encouraged. If you have personal issues that prohibit you from joining freely in class discussion, e.g., shyness, language barriers, etc., that is no problem! Let me know me as soon as possible and we will discuss alternative modes of participation.
    
  **If you need to miss an assignment or discussion for whatever reason (conference, illness, family emergency, etc.), please let me know as soon as possible.** We will make arrangements for you to complete any assignments and go over any course material you will be missing. I would much rather you focus on your health or supporting friends and family in need than struggle to turn in assignments. Let me know so we can work things out.

**4. Grading Scale**

  * **Grade Assignment** (based on % of possible points)  
      
      A = 94–100%, A- = 90–93%  
      B+ = 87–89%, B = 84–86%, B- = 80–83%  
      C+ = 77–79%, C = 74–76%, C- = 70–73%  
      D+ = 67–69%, D = 64–66%, D- = 60–63%   
      E	< 60  

   * **Regrades:** Requests for re-evaluation of any quizzes, exams, or assignments will only be considered if accompanied by a letter explaining why you think you deserve additional credit and the number of additional points you think you deserve.  The deadline for submitting these requests is one week after the work has been returned.

  * **Grade Points:** For information on how UF assigns grade points, visit: https://catalog.ufl.edu/UGRD/academic-regulations/grades-grading-policies/
    
### IV. Quest Learning Experiences

**5. Details of Experiential Learning Component**

   This course has multiple experiential learning activities. Students will be taking a field trip to the FLMNH Butterfly Rainforest to investigate plant form and function and plant animal interactions. Students will also be keeping a log of all tropical products used during three 24-hour intervals. Finally, they will be gathering and analyzing data on deforestation, biodiversity in different tropical rain forest regions, and  for forest regeneration influences carbon stocks and climate change scenarios. 

**6. Details of Self-Reflection Component**
    
  Students will also have multiple opportunities for self-reflection throughout the course. In addition to reflection on their goals and expectations for the class, they will consider the (almost certainly underappreciated) ubiquity of products derived from tropical plants and animals in their daily lives. Finally, they will have the opportunity to consider what actions they can take as individuals to advance rain forest conservation and the well-being of forest-dependent people.

### V. General Education and Quest Objectives & SLOs

**7. Course Objectives — GenEd Primary Area & Quest **

**8. Course Student Learning Outcomes (SLOs) — GenEd Primary Area & Quest **

**9. Secondary Objectives and SLOs (Optional)**

   * International Objectives (for N co-designation)

  * International Student Learning Outcomes (for N co-designation)

### VI. Required Policies 

**10. Students Requiring Accommodation**

  Students with disabilities who experience learning barriers and would like to request academic accommodations should connect with the Disability Resource Center by visiting https://disability.ufl.edu/students/get-started/. It is important for students to share their accommodation letter with their instructor and discuss their access needs, as early as possible in the semester. 

**11. UF Evaluations Process**

   Students are expected to provide professional and respectful feedback on the quality of instruction in this course by completing course evaluations online via GatorEvals. Guidance on how to give feedback in a professional and respectful manner is available at https://gatorevals.aa.ufl.edu/students/. Students will be notified when the evaluation period opens, and can complete evaluations through the email they receive from GatorEvals, in their Canvas course menu under GatorEvals, or via https://ufl.bluera.com/ufl/. Summaries of course evaluation results are available to students at https://gatorevals.aa.ufl.edu/public-results/.

**12. University Honesty Policy** 

   UF students are bound by The Honor Pledge which states, “We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code. On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied: “On my honor, I have neither given nor received unauthorized aid in doing this assignment.” The Honor Code (https://www.dso.ufl.edu/sccr/process/student-conduct-honor-code/) specifies a number of behaviors that are in violation of this code and the possible sanctions. Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel. If you have any questions or concerns, please consult with the instructor or TAs in this class.  

**13. Counseling and Wellness Center**
  
  Contact information for the Counseling and Wellness Center: http://www.counseling.ufl.edu/cwc/Default.aspx, 392-1575; and the University Police Department: 392-1111 or 9-1-1 for emergencies.  

**14. The Writing Studio**  
    
    * The writing studio is committed to helping University of Florida students meet their academic and professional goals by becoming better writers. Visit the writing studio online at http://writing.ufl.edu/writing-studio/ or in 2215 Turlington Hall for one-on-one consultations and workshops.  
