---
title: 'IDS 2935 - Disturbances in Tropical Forests: In-class Activity'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{In-Class: Disturbances, p. \thepage}
- \fancyhead[L]{IDS 2935 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output: html_document
# output:
#   pdf_document: default
#   html_document:
#     df_print: paged
#   rmdformats::robobook: default
# editor_options: 
#   markdown: 
#     wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disturbances in Tropical Forests
\vspace{0.3cm}

### Introduction

We learned that the number of species found in a given location on earth varies geographically, with species richness increasing as one approaches the equator - a pattern called the **Latitudinal Diversity Gradient**. Figuring out the mechanisms responsible for the **_origins_ of tropical diversity** is a major topic of research in ecology and evolutionary biology. Now we will try to understand how all these species manage to coexist and persist in tropical forests - i.e., the mechanisms responsible for the **_maintenance_ of tropical diversity**. After all, lots of theoretical and empirical research by ecologists has shown that when two species compete for the same resource, the superior competitor should outcompete the inferior competitor...unless there is some mechanism that allows it to persist. Before hypothesizing about potential mechanisms of coexistance, however, we first need to set the stage for the discussion by diving into some data to learn about another ubiquitous pattern observed in tropical rain forests. 

We will be using data from one of the most studied tropical forests in the world - the Smithsonian Tropical Research Institute's "Barro Colorado Island". This island, created by the flooding of the panama canal, has a 50-ha plot (1000 m x 500 m) in which every single tree with a diameter > 1 cm has been marked and identified. The plot is censused every 5-10 years to track the recruitment, growth, and death of trees. The original file has over 6.7 million pieces of information about these trees in it, but I prepared a summary with the information needed for today's exercise. [If you're interested in taking a look at these data, or maybe even doing some research with them, let me know].

**Step 1: **Download this file to your computer. It is a table with two columns: (1) the name of every tree species found in the plot in the 2005 survey and (2) how many individuals of that species were found in the plot. 

**Step 2: **Import the data into a Google Sheet or Microsoft Excel spreadsheet. (the hints below assume you are working with google sheets).


**Questions: **

1) How many total trees (all species combined) are there in the plot?

2) How many species of trees are in the plot?

3) What is the most common species, and how many individuals does it have?

4) If you arrange the species in order from most abundant to least abundant, how many species do you need to include until you have counted 50% of the trees in the plot? (hint: you'll first have to make a column of the cumulative frequency, then a column of the  cumulative percentage. If you need help figuring this out, ask for it!).

5) If you arrange the species in order from least abundant to most abundant and select the 50% of species that are the *least* abundant, what fraction of the trees in the plot do they represent? 

6) How many species are represented by only 1 individual?

7) Create a figure (bar or column chart) in which the x axis is each tree species and the y axis is the number of individuals of that species. What does that plot tell you about the relative abundance of tree species in tropical forests? (hint: highlight the "count" and "species" columns, select "Insert" from the menu ribbon, and then drop down to chart. It will probably make a pie chart as a default - to the right under "setup" select the drop down menu for "chart type" select "column chart" (Don't ever use pie charts. Ever. They're awful. Ask me why.). 

8) Save the figure of frequency x species: click it, then click the 3 dots in the top right corner. Select "download" -> "PDF document".)

**Submit your answers to these questions and your plot via canvas. **







